services:
  livekit:
    build:
      context: ./livekit-server
      dockerfile: Dockerfile
    container_name: letslearn_livekit
    ports:
      - "8111:8111"

  tldraw:
    build:
      context: ./tldraw-server
      dockerfile: Dockerfile
    container_name: letslearn_tldraw
    ports:
      - "5858:5858"

  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    container_name: letslearn_server
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16.3
    restart: always
    container_name: letslearn_db
    shm_size: 64mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: lets-learn
    volumes:
      - db_data:/var/lib/postgresql/data
    expose:
      - "5432"
    ports:
      - "8888:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 5

volumes:
  db_data:
